swagger: "2.0"
info:
  description: Actualiza los cambios en el Sistema Remedy y Oracle CMDB
  version: "1.0.0"
  title: API Actualiza cambios
host: remedy-update-prod.cloudapp.qa.prosa.lat:8080
basePath: /remedy-update/v1

securityDefinitions:
  Bearer:
    description: >
      Para acceder a la API se debe pasar un token válido en todas las consultas.
      La siguiente sintaxis se debe utilizar en el encabezado 'Authorization' :
        Bearer: 2zzLJmBAtTNIU8nF8e8XbmDvaNGs
    type: apiKey
    name: Authorization
    in: header
    
security:
  - Bearer: []

paths:
 
  /updates:
    put:
      tags:
        - sincronización
      summary: Actualiza los cambios en Remedy y Oracle CMDB
      description: |-
        Actualiza los cambios en Remedy y Oracle CMDB
      consumes:
      - "application/json"
      produces:
        - application/json
      
      parameters:
      - in: "body"
        name: "body"
        description: "Pet object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/ListaCambios"
      - name: Context-type
        in: "header"
        description: "Tipo de objeto enviado"
        required: true
        type: string
        format: utf-8
      - name: Authorization
        in: "header"
        description: "Contiene las credenciales para identificar a el usuario en un servidor."
        required: true
        type: string
        format: string
      - name: X-Forwarded-For
        in: "header"
        description: "Indica la dirección IP original del cliente, para cuando hay un enrutador y cambia la dirección de quien es la petición o la respuesta originalmente"
        required: true
        type: string
        format: ip-address
      - name: X_Fowareded-Host
        in: "header"
        description: "El nombre de dominio del servidor reenviado."
        required: true
        type: string
        format: http-url

      responses:
        201:
          description: OK
          
        400:
          description: Error en la petición.
          schema:
            $ref: "#/definitions/ResponseBadRequest"
          examples:
            application/json:
              {
                "codigo": "400",
                "mensaje": "Error en la petición.",
                "information": {}
              }
        403:
          description: No autorizado.
          schema:
            $ref: "#/definitions/ResponseForbidden"
          examples:
            application/json:
              {
                "codigo": "403",
                "mensaje": "No autorizado.",
                "information": {}
              }
        500:
          description: Operación Inesperada
          schema:
            $ref: "#/definitions/ResponseNotFound"
          examples:
            application/json:
              {
                "codigo": "500",
                "mensaje": "Ocurrió un error en el servidor",
                "information": {}
              }
          
      security:
        - Bearer: []
definitions:

  ListaCambios:
    type: "object"
    properties:
      updates:
        type: "array"
        items:
          type: "object"
          $ref: "#/definitions/CambiosTO"
  
  CambiosTO:
    type: object
    properties:
      id:
        type: integer
        description: Identificador único del componente modificado
        example: 2
      dsCode:
        type: string
        description: descripción del código
        example: 16876
      dsName:
        type: string
        description: Nombre del componente
        example: "BUSINESSPROCESS"
      dtCreation:
        type: string
        description: fecha en que se creo el componente en el sistema Mega
        example: '2018-06-20T07:22:09Z'
      dtModified:
        type: string
        description: fecha en que se modifico el componente en el sistema Mega
        example: '2018-06-20T07:22:09Z'
      userCreation:
        type: string
        description: Usuario que creo el documento
        example: "Mario Balbuena Juarez"
      userModification:
        type: string
        description: Usuario que modifico el documento
        example: "Mario Balbuena Juarez"
      cambios:
        type: string
        description: Nombre de campos y datos de los elementos que se modificaron
        example: "{nombreSite: Santa Fe, estatus: 1, descripcion: Se actualizo licencia de server  }"
       
  ResponseForbidden:
    type: object
    properties:
      codigo:
        type: integer
        description: Codigo de error
        example: "403"
      mensaje:
        type: string
        description: Mensaje de error para el desarrollador
        example: "No autorizado."
      information:
        type: object
        description: Objeto que contiene mas información acerca del error.

  ResponseBadRequest:
    title: Response Bad Request
    type: object
    properties:
      code:
        type: integer
        description: Codigo de error de la petición
        example: 400
      message:
        type: string
        description: Mensaje de error para el desarrollador
        example: "Datos incorrectos"
      information:
        type: object
        description: Objeto que contiene mas información acerca del error.

  ResponseNotFound:
    type: object
    properties:
      code:
        type: integer
        description: Codigo de error de la petición
        example: 404
      message:
        type: string
        description: Mensaje de error para el desarrollador
        example: "No se encontró información"
      information:
        type: object
        description: Objeto que contiene mas información acerca del error.  