



DROP SEQUENCE IF EXISTS SEQ_COMPONENTE_RED;
DROP SEQUENCE IF EXISTS SEQ_IPS;
DROP SEQUENCE IF EXISTS SEQ_NIVEL_CIFRADO;
DROP SEQUENCE IF EXISTS SEQ_PROTOCOLO;

CREATE SEQUENCE IF NOT EXISTS SEQ_COMPONENTE_RED START WITH 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_IPS START WITH 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_NIVEL_CIFRADO START WITH 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_PROTOCOLO START WITH 1;



